---
name: "Configuration Validation"
category: "000-099"
description: "Standards for validating project configuration"

security_context:
  type: "Personal Project"
  description: "This is a personal garage project with no other users or access requirements."

validation_requirements:
  node_version:
    minimum: "20.x"
    validation:
      - "Check process.versions.node"
      - "Verify package.json engines field"
      - "Ensure tsconfig.json targets ES2020+"

  module_system:
    type: "ES Modules"
    requirements:
      - "package.json type: module"
      - "ESM import/export syntax"
      - "import.meta.url for paths"
    files:
      - name: "webpack.config.js"
        format: "ESM"
        requirements:
          - "export default configuration"
          - "import.meta.url for paths"
          - "proper module resolution"
      
      - name: "tsconfig.json"
        format: "JSON"
        requirements:
          - "module: ESNext"
          - "moduleResolution: bundler"
          - "esm: true in ts-node config"

  babel_config:
    format: ".babelrc.json"
    requirements:
      - "ES module support"
      - "TypeScript support"
      - "Vue 3 compatibility"

validation_script:
  path: "scripts/validate-config.ts"
  checks:
    - "Node.js version ≥20.x"
    - "ES module configuration"
    - "Webpack config format"
    - "Babel config presence"
    - "Package.json settings"
  exit_codes:
    0: "All checks passed"
    1: "Validation failed"

error_handling:
  strategy:
    - "Detailed error messages"
    - "Specific validation failures"
    - "Clear resolution steps"
  logging:
    - "Validation progress"
    - "Failed checks"
    - "Configuration state"

best_practices:
  - "Run validation before commits"
  - "Keep configuration files in sync"
  - "Document configuration changes"
  - "Test after dependency updates"

cross_references:
  - "005.1-webpack-esm-resolution.yaml"
  - "100-dev-workflow.yaml#development_environment"
  - "500-webpack-deploy.yaml#webpack_configuration"
  - "300-testing.yaml#phase_specific_testing" 